### ISSUE TITLE
Provide The Graph node endpoint with example

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iott-dapp-example#5]
Please provide the endpoint for connecting to the Trustream The Graph node, and a simple Javascript sample code for fetching the Pebble data

**Comment by maswalker** [comment]
This document describes how to use the graph node of iotex.
https://iotex.larksuite.com/docs/docusy3KTy6aHoHa1zoYYr3BwIb#

And I modified README accordingly.
https://github.com/iotexproject/iott-dapp-example/blob/main/subgraph/README.md

**Comment by simonerom** [comment]
Hey, @maswalker, I'm afraid you misunderstood my request here (or I have a wrong understanding of the architecture):

The Graph node and the respective subgraph for indexing Pebble Data **should already be deployed** by us (part of the TruStream architecture); is this correct?

So, from the point of view of an IOTT Dapp developer, he is only interested in **fetching the data** from our Graph node, not interested in deploying the node or the subgraph. 
So what I need to provide them is:

1) the endpoint of the Graph node devs must use to query
2) a javascript example of querying Pebble Data

For example, if the developers use the Apollo GraphQL client to query, how should the query look like? 
```
const GRAPHNODEURL = "<what's the endpoint?>";

const pebbleQuery = `
  query {
     // what are the fields to be queried?
  }
```

Please let me know if I've misunderstood things on my side!

**Comment by maswalker** [comment]
I add an example to access graphql
https://github.com/iotexproject/iott-dapp-example/blob/main/dapp/src/graphql.example.ts

**Comment by simonerom** [comment]
Thanks
